# Generated by Django 2.1.4 on 2019-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('author_name', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
